"""empty message

Revision ID: 0d570b9a7857
Revises: e005ad8010f1
Create Date: 2020-10-15 14:11:02.372913

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '0d570b9a7857'
down_revision = 'e005ad8010f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_ = 'foreignkey')
    # ### end Alembic commands ###
