"""Whoosh

Revision ID: 0fbf188a9760
Revises: 1129d4de25ec
Create Date: 2020-08-28 22:15:39.582418

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '0fbf188a9760'
down_revision = '1129d4de25ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_ = 'foreignkey')
    # ### end Alembic commands ###
