"""empty message

Revision ID: 1f836d093701
Revises: ef8e70f0dee9
Create Date: 2020-08-23 00:52:21.773077

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '1f836d093701'
down_revision = 'ef8e70f0dee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_ = 'foreignkey')
    # ### end Alembic commands ###
