"""empty message

Revision ID: 9743d48ded13
Revises: 1c5cddbcc8eb
Create Date: 2020-08-23 00:21:35.614712

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9743d48ded13'
down_revision = '1c5cddbcc8eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable = False),
                    sa.Column('name', sa.String(length = 64), nullable = True),
                    sa.Column('default', sa.Boolean(), nullable = True),
                    sa.Column('permissions', sa.Integer(), nullable = True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique = False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name = 'roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
