"""empty message

Revision ID: 9a068e04dd67
Revises: 5718a422eab5
Create Date: 2020-08-23 01:53:50.867239

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9a068e04dd67'
down_revision = '5718a422eab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length = 64), nullable = True))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_ = 'foreignkey')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
