"""empty message

Revision ID: 9f2647d57df8
Revises: 0fbf188a9760
Create Date: 2020-08-28 22:22:19.090321

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '9f2647d57df8'
down_revision = '0fbf188a9760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_ = 'foreignkey')
    # ### end Alembic commands ###
