"""empty message

Revision ID: ab97844e3a19
Revises: 07c8200e91cc
Create Date: 2020-08-23 19:40:21.546947

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ab97844e3a19'
down_revision = '07c8200e91cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_ = 'foreignkey')
    # ### end Alembic commands ###
