"""Whoosh2

Revision ID: e005ad8010f1
Revises: 9f2647d57df8
Create Date: 2020-08-28 22:51:00.287853

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e005ad8010f1'
down_revision = '9f2647d57df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_ = 'foreignkey')
    # ### end Alembic commands ###
